USE myCarDealership;
GO;

ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_ZipCode FOREIGN KEY(ZipCode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO
ALTER TABLE Sales WITH CHECK
ADD CONSTRAINT FK_LocationID FOREIGN KEY(LocationID) REFERENCES Location(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Sales WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(ID)
ON UPDATE CASCADE
GO
ALTER TABLE SalesDetail
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID) REFERENCES Sales(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE SalesDetail
ADD CONSTRAINT FK_InventoryNumber FOREIGN KEY(InventoryNumber) REFERENCES Inventory(carID)
ON UPDATE CASCADE
GO
